FROM node:20.18-alpine

WORKDIR /app

COPY package*.json ./

COPY tsconfig.json ./

RUN npm i -g serve

RUN npm install

COPY . .

RUN mkdir -p dist

RUN npm run build

EXPOSE 8080

CMD [ "serve", "-s", "dist" ]