name: Build and Push Docker Compose Images

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true  # Ensure Buildx is installed and set up

      # Build and push frontend service
      - name: Build and push frontend service
        uses: docker/build-push-action@v4
        with:
          context: ./frontend  # Path to your frontend Dockerfile directory
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      # Build and push backend service
      - name: Build and push backend service
        uses: docker/build-push-action@v4
        with:
          context: ./backend  # Path to your backend Dockerfile directory
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Log out from Docker Hub
        run: docker logout
